# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-08 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cats_or_dogs',
            field=models.CharField(choices=[('C', 'Cat'), ('D', 'Dog')], default='D', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_colour',
            field=models.CharField(blank=True, default="I'm boring, I don't like colours.", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobby',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
