# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-10 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191009_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='owls/glassesowl.png', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cats_or_dogs',
            field=models.CharField(choices=[('Cats', 'Cats'), ('Dogs', 'Dogs')], default='Dogs', max_length=4),
        ),
    ]
